In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('D:\Practice Ml models\Car price Predictino\cardekho_imputated.csv')

In [3]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [4]:
df.describe()

,Unnamed: 0,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,9811.857699,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,5643.418542,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4906.500000,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9872.000000,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,14668.500000,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [7]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [8]:
df.isna().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [10]:
# droping the columns which are not neccesary 
df.drop(columns=['car_name', 'brand'], inplace= True, axis=1)

In [36]:
# Numerical features 
num_features = df.select_dtypes(include=[np.number]).columns.tolist()
print("Total no of numerical features :- ", len(num_features))

# Categorical features 
cat_features = df.select_dtypes(include=[object]).columns.tolist()
print("Total no of categorical features :- ",len(cat_features))

# Discrete features 
discrete_features = df.select_dtypes(include=['int64']).columns.tolist()
print("Total no of discrete features :- ", len(discrete_features))

#continous features 
continuus_features = df.select_dtypes(include=['float64']).columns.tolist()
print("Total no of continuos features :- ", len(continuus_features))

Total no of numerical features :-  8
Total no of categorical features :-  4
Total no of discrete features :-  6
Total no of continuos features :-  2

In [43]:
from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'], axis=1)
y = df['selling_price']

In [46]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [48]:
# Creating columns Transformer with 3 types of transformer 
num_features = X.select_dtypes(exclude="object").columns
onehot_columns = ['seller_type', 'fuel_type', 'transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer 

numeric_transformer = StandardScaler()
oh_transformer =OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("standardScaler", numeric_transformer, num_features)
    ],
    remainder= 'passthrough'
)

In [49]:
X = preprocessor.fit_transform(X)

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state= 42,test_size=0.3)

In [52]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.282437,0.297421,-0.675807,-0.283173,0.105211,0.022918,-0.276654,-0.403022
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.736659,1.536377,0.319814,1.247335,0.680595,-0.172826,-0.275956,-0.403022
2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.154682,-0.831405,0.651688,1.053600,0.040480,-0.048087,-0.390683,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.331750,0.710406,-0.343933,0.084924,0.167544,-0.554718,-0.406740,-0.403022
4,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.417997,0.958197,-0.343933,-0.535028,-0.645185,0.201390,0.481987,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10782,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.572519,-0.556082,0.319814,1.397111,0.256249,-0.456846,-0.274327,2.073444
10783,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.278902,0.903133,1.647309,0.065551,-0.865749,0.214823,0.060778,-0.403022
10784,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.526800,1.040794,0.319814,-0.690016,0.193916,-0.936610,-0.780708,-0.403022
10785,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.543061,1.536377,-1.339555,-0.786884,-0.263994,-0.554718,-0.435829,-0.403022
10786,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.091589,-1.051664,-1.339555,-0.496281,0.138775,-0.046168,0.061942,-0.403022

##### Model Training

In [72]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import root_mean_squared_error

def evaluate_model(true, predicted):
    mse = mean_squared_error(true, predicted)
    mae = mean_absolute_error(true, predicted)
    rmse = root_mean_squared_error(true, predicted)
    r2 = r2_score(true, predicted)

    return mse, mae, rmse, r2

In [73]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor()
}

for name, model in models.items():

    # Train model
    model.fit(X_train, y_train)

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluation
    model_train_mse, model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(
        y_train, y_train_pred
    )

    model_test_mse, model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(
        y_test, y_test_pred
    )

    print(name)

    print("Model performance for Training set")
    print("- MSE: {:.4f}".format(model_train_mse))
    print("- RMSE: {:.4f}".format(model_train_rmse))
    print("- MAE: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print("----------------------------------")

    print("Model performance for Test set")
    print("- MSE: {:.4f}".format(model_test_mse))
    print("- RMSE: {:.4f}".format(model_test_rmse))
    print("- MAE: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print("=" * 50)
    print()

Linear Regression
Model performance for Training set
- MSE: 312821017452.9695
- RMSE: 559304.0474
- MAE: 268442.9036
- R2 Score: 0.6183
----------------------------------
Model performance for Test set
- MSE: 257660096374.1551
- RMSE: 507602.3014
- MAE: 281392.3292
- R2 Score: 0.6574
==================================================

Lasso
Model performance for Training set
- MSE: 312821029031.6092
- RMSE: 559304.0578
- MAE: 268441.8096
- R2 Score: 0.6183
----------------------------------
Model performance for Test set
- MSE: 257659028080.0050
- RMSE: 507601.2491
- MAE: 281388.5901
- R2 Score: 0.6574
==================================================

Ridge
Model performance for Training set
- MSE: 312821960701.6804
- RMSE: 559304.8906
- MAE: 268398.1907
- R2 Score: 0.6183
----------------------------------
Model performance for Test set
- MSE: 257641767654.0622
- RMSE: 507584.2469
- MAE: 281336.6999
- R2 Score: 0.6574
==================================================

K-Neighbors Regressor
Model performance for Training set
- MSE: 120478027084.4535
- RMSE: 347099.4484
- MAE: 98310.4107
- R2 Score: 0.8530
----------------------------------
Model performance for Test set
- MSE: 99658633606.3203
- RMSE: 315687.5569
- MAE: 126607.8990
- R2 Score: 0.8675
==================================================

Decision Tree
Model performance for Training set
- MSE: 0.0000
- RMSE: 0.0000
- MAE: 0.0000
- R2 Score: 1.0000
----------------------------------
Model performance for Test set
- MSE: 113936353431.1473
- RMSE: 337544.5947
- MAE: 133774.8432
- R2 Score: 0.8485
==================================================

Random Forest Regressor
Model performance for Training set
- MSE: 17392229085.5474
- RMSE: 131879.6007
- MAE: 36648.7680
- R2 Score: 0.9788
----------------------------------
Model performance for Test set
- MSE: 61749488767.8687
- RMSE: 248494.4441
- MAE: 102303.3791
- R2 Score: 0.9179
==================================================

In [74]:
#Initialize few parameter for Hyperparamter tuning
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]}
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

In [75]:
# Models list for Hyperparameter tuning
randomcv_models = [('KNN', KNeighborsRegressor(), knn_params),
                   ("RF", RandomForestRegressor(), rf_params)
                   
                   ]

In [76]:
##Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 100 candidates, totalling 300 fits
---------------- Best Params for KNN -------------------
{'n_neighbors': 2}
---------------- Best Params for RF -------------------
{'n_estimators': 1000, 'min_samples_split': 2, 'max_features': 8, 'max_depth': None}

In [78]:
## Retraining the models with best parameters
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=1000, min_samples_split=2, max_features=8, max_depth=None, 
                                                     n_jobs=-1),
     "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=2, n_jobs=-1)
    
}
for name, model in models.items():

    # Train model
    model.fit(X_train, y_train)

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluation
    model_train_mse, model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(
        y_train, y_train_pred
    )

    model_test_mse, model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(
        y_test, y_test_pred
    )

    print(name)

    print("Model performance for Training set")
    print("- MSE: {:.4f}".format(model_train_mse))
    print("- RMSE: {:.4f}".format(model_train_rmse))
    print("- MAE: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print("----------------------------------")

    print("Model performance for Test set")
    print("- MSE: {:.4f}".format(model_test_mse))
    print("- RMSE: {:.4f}".format(model_test_rmse))
    print("- MAE: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print("=" * 50)
    print()

Random Forest Regressor
Model performance for Training set
- MSE: 17453994512.3021
- RMSE: 132113.5667
- MAE: 35319.1861
- R2 Score: 0.9787
----------------------------------
Model performance for Test set
- MSE: 54700770020.4548
- RMSE: 233881.9574
- MAE: 98279.7105
- R2 Score: 0.9273
==================================================

K-Neighbors Regressor
Model performance for Training set
- MSE: 54187559400.2039
- RMSE: 232782.2145
- MAE: 70219.5699
- R2 Score: 0.9339
----------------------------------
Model performance for Test set
- MSE: 103613603512.2459
- RMSE: 321890.6701
- MAE: 128179.4172
- R2 Score: 0.8622
==================================================